export const Customimages ={
flash: require('../asset/images/flash.png'),
vactorimg: require('../asset/images/Vactorimg.png'),
back: require('../asset/images/back.png'),
downarrow: require('../asset/images/downarrow.png'),
downarrow1: require('../asset/images/downarrow1.png'),
map: require('../asset/images/map.png'),
notification: require('../asset/images/notification.png'),
search: require('../asset/images/search.png'),
fimages: require('../asset/images/fimages.png'),
f1images: require('../asset/images/f1images.png'),
f2images: require('../asset/images/f2images.png'),
f3images: require('../asset/images/f3images.png'),
file: require('../asset/images/file.png'),
profile: require('../asset/images/profile.png'),
home: require('../asset/images/home.png'),
sell: require('../asset/images/sell.png'),
requests: require('../asset/images/request.png'),
profile1: require('../asset/images/profile1.png'),
edit: require('../asset/images/edit.png'),
money: require('../asset/images/money.png'),
mycrop: require('../asset/images/mycrop.png'),
setting: require('../asset/images/setting.png'),
notification1: require('../asset/images/notification1.png'),
payment: require('../asset/images/payment.png'),
Language: require('../asset/images/Language.png'),
language1: require('../asset/images/language1.png'),
customer: require('../asset/images/customer.png'),
forwordspace: require('../asset/images/forwordspace.png'),
homeimage: require('../asset/images/homeimage.png'),
shareicon: require('../asset/images/shareicon.png'),
reward: require('../asset/images/reward.png'),
invate: require('../asset/images/invate.png'),
logout: require('../asset/images/logout.png'),
flag: require("../asset/images/flag.png"),
grassbottom: require("../asset/images/grassbottom.png"),
lightimg: require("../asset/images/lightimg.png"),
x:require("../asset/images/x.png"),
agrolixlogo:require("../asset/images/agrolix-logo.png"),

} 


